### ISSUE TITLE
LambdaExpr left side too permissive

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1017]
This is accepted: `class X{int x(){ a(1+1 -> 10);}}`

Maybe add a validation to check this.

**Comment by jlerbsc** [comment]
In JP 3.16.1 this test case generate a parsing  error

    Failed to parse lambda expression! Please create an issue at https://github.com/javaparser/javaparser/issues]

So i think this issue is resolved.

**Comment by matozoid** [comment]
Oh, I don't think that particular error should ever be shown! It is there to see if bugs remain in the lambda parsing implementation.

**Comment by jlerbsc** [comment]
Hi @matozoid Do you want this issue to remain open?

**Comment by matozoid** [comment]
Do as you please (open a new issue?) - but this error is never supposed to happen.
