### ISSUE TITLE
methodDeclaration.getJavaDoc() returns null 

### ISSUE THREAD

**Issue by kronar** [javaparser/javaparser#141]
CompilationUnit cu = JavaParser.parse(f);
List<TypeDeclaration> types = cu.getTypes();
List<ImportDeclaration> imports = cu.getImports();
Assert.assertNotNull(imports);

**Comment by ftomassetti** [comment]
Yes, this is known: lists are initialized with null and nothing prevent to call setters for lists with null.
I wanted to correct this behavior (see #54 and #106) but the PR has been stuck for a while.

Until it gets fixed (if we agree on fix it) you should expect every getters returning a list to treat null or empty lists as equivalent.

**Comment by kronar** [comment]
@ftomassetti I've mean that after parsing class with imports  this list is still empty

**Comment by ftomassetti** [comment]
I think it is the expected behavior, if the class has no imports because instead of assigning empty lists we leave them uninitialized (so with value null)

**Comment by ftomassetti** [comment]
if instead the file contains imports than it is a new bug, in that case please post the source code

**Comment by kronar** [comment]
I've created project that reproduces this issue
https://github.com/kronar/javaparser-issue-141

mvn clean test

**Comment by ftomassetti** [comment]
Thank you for creating the example: best bug report ever!

About the issue: for me the test pass, and the test verifies that the imports are not null and not empty. I tried parsing the given class (https://github.com/kronar/javaparser-issue-141/blob/master/src/main/java/ClassToParse.java) and I can see that the `getImports` return a list of one element, as expected.

Modifying your test to print the imports:

```
    @Test
    public void testIssue141() throws IOException, ParseException {
        CompilationUnit parse = JavaParser.parse(new File("./src/main/java/ClassToParse.java"));
        List<ImportDeclaration> imports = parse.getImports();
        System.out.println("IMPORTS "+imports);
        Assert.assertNotNull(imports);
        Assert.assertFalse(imports.isEmpty());
    }
```

I get:

```
IMPORTS [import com.google.common.base.Optional;
]
```

Am I not understanding the issue or we have a bug that happens just in your environement? Let me know if I can help in figuring out this one, I am curious.

**Comment by kronar** [comment]
Seems it's my fault.
I've fixed test case. 
Javadoc is null. See latest commits

**Comment by ftomassetti** [comment]
I updated the title of the issue. Yes, I can reproduce the issue. You can get the comment using the method getComment() instead of getJavaDoc().

I will look more into this to understand why this happens.

**Comment by Parth** [comment]
Hi,
I just wanted to get a status on this issue. I see that some pull requests were merged. I'm currently using `<version>2.2.2</version>` from maven, and I'm still experiencing this issue. For me the only way to access the javadoc comments is by going through `MethodDeclaration.getComments()`. And `MethodDeclaration.getJavaDoc()` still returns null.

Is there a version that has this fix available in maven? Or is a pull request still necessary? I would be happy to help out if a pull request is necessary to resolve this issue.
Thanks,
Parth

**Comment by ftomassetti** [comment]
Hi @Parth-Mehrotra unfortunately we did not yet fix this. A pull-request would be very welcome and we are always happy to get new contributors. Let me know if you need any help with the PR.

**Comment by matozoid** [comment]
@ftomassetti after looking at the JavaDoc related code, it seems that it was part of a large comments related change in 2013 (3f2c603c). Looks like it was going to be implemented, but then half rolled back. None of the JavaDoc fields are ever set. Since your name is on it I'd like to ask if it is okay to remove everything related to JavaDoc for now. (I wouldn't know how to implement it. Could be moved to a new issue)

**Comment by ftomassetti** [comment]
It is amazing how things emerging from ancient history can confuse us all :)
Probably we could implement `getJavaDoc` to take the result of `getComment` and check if it is an istance of `JavaDocComment`. If that it the case that value could be casted returned, otherwise null should be returned instead (we are stuck to Java 6 so no Optional for us). This would be fairly easy to do and probably simplify the life of people looking just for JavaDoc comments.
Thoughts?

**Comment by matozoid** [comment]
It seems like a nice idea - how would this work with visitors? Won't anything be visited twice?

**Comment by ftomassetti** [comment]
Probably you should visit only Comment and not JavaDoc, because it would be a derived field
