### ISSUE TITLE
Comments within methods not getting parsed

### ISSUE THREAD

**Issue by mahendrakariya** [javaparser/javaparser#192]
The java class that we want to parse looks like this.

```
public class StepImplementation {
    @Step("A step")
    public void contextStep() {
        // Foo bar
    }
}
```

When we parse this class using `JavaParser.parse`, the comments are ignored.
`CompilationUnit.toString()` prints the following output. Notice that the comments within the method `contextStep()` is not there.

```
public class StepImplementation {
    @Step("A step")
    public void contextStep() {
    }
}
```

**Comment by ftomassetti** [comment]
It seems a duplicate of #181 . Which version are you using?

**Comment by mahendrakariya** [comment]
Thanks for the quick reply. It is indeed a duplicate of #181. We are using version 2.2.1. Looks like you guys have fixed it in the master, but are yet to release it.

**Comment by SmiddyPence** [comment]
2.2.2 available.

should be resolved.

**Comment by mahendrakariya** [comment]
Thanks for making the release. But even in v2.2.2, the issue is not resolved.
Below are the test cases that I tried.

**Case # 0:**
_Comments_ **_are not**_ _getting parsed_

```
public class StepImplementation {
    @Step("A step")
    public void contextStep() {
        // Foo bar
    }
}
```

**Case # 1:** 
_Comments_ **_are not**_ _getting parsed_

```
    public void contextStep() {
        for (int i = 0; i < 5; i++) {
            System.out.println();
            // foo bar
        }
    }
```

**Case # 2:**
_Comments_ **_are not**_ _getting parsed_

```
    public void contextStep() {
        for (int i = 0; i < 5; i++) {
            // foo bar
        }
    }
```

**Case # 3:**
_Comments_ **_are**_ _getting parsed_

```
    public void contextStep() {
        for (int i = 0; i < 5; i++) {
            // foo bar
            System.out.println();
        }
    }
```

**Case # 4:**
**_Only some**_ _of the comments_ **_are**_ _getting parsed_

```
    public void contextStep() {
        for (int i = 0; i < 5; i++) {
            // foo bar
            System.out.println();
            // another foo bar
        }
    }
```

The `compilationUnit.toString()` for the above code prints the following.

```
    public void contextStep() {
        for (int i = 0; i < 5; i++) {
            // foo bar
            System.out.println();
        }
    }
```

It looks like if there is an executable line of code after the comments, they are parsed. Otherwise, they are ignored.

**Comment by SmiddyPence** [comment]
I suspect they're recorded as orphan comments.

Here is a further explanation:

https://github.com/javaparser/javaparser/wiki/Comments-%28Attribution%29

**Comment by ptitjes** [comment]
@mahendrakariya DumpVisitor lakes correct printing of so-called 'orphan comments' in many types of AST nodes. It can be fixed by adding calls to printOrphanComments() here and there in DumpVisitor. Note however that this technique is not intended to print out comments, statements and expressions in the order that they were read. Nor is it designed to print out code and comments in the way they were formatted when read.

In the mean time, you might want to try **[JLaTo](https://github.com/ptitjes/jlato)**, a parser for Java 1.8 that supports **full lexical preservation** (including whitespaces and comments) and **configurable formatting** for added/modified AST nodes.

**Comment by mahendrakariya** [comment]
Thanks for the prompt response.

We are trying to get the orphan comments from `MethodDeclaration`, but are somehow unable to. `method.getOrphanComments().size()` is always returning 0. Below is the code. Are we doing something wrong?

```
public class JavaParserTest {
    public static void main(String[] args) throws IOException {
        JavaParserTest j = new JavaParserTest();
        CompilationUnit cu = null;
        try {
            cu = JavaParser.parse(j.getClass().getClassLoader().getResourceAsStream("StepImplementation.java"));
        } catch (ParseException e) {
            e.printStackTrace();
        }
        analyzeMethods(cu);
    }

    private static void analyzeMethods(CompilationUnit cu) {
        List<TypeDeclaration> types = cu.getTypes();
        for (TypeDeclaration type : types) {
            List<BodyDeclaration> members = type.getMembers();
            for (BodyDeclaration member : members) {
                if (member instanceof MethodDeclaration) {
                    MethodDeclaration method = (MethodDeclaration) member;
                    analyzeMethod(method);
                }
            }
        }
    }

    private static void analyzeMethod(MethodDeclaration method) {
        System.out.println(method.getOrphanComments().size());
    }
}
```

**StepImplementation.java**

```
public class StepImplementation {
    public void doFooBar() {
        // This is a comment
        System.out.println();

        // This is an orphan comment
    }
}
```

**Comment by ftomassetti** [comment]
Given this seems not to be solved I will reopen it

**Comment by ftomassetti** [comment]
@mahendrakariya 
The orphan comment in Case #0 is in the body of the comment:

```
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseException;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Node;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

/**
 * Created by federico on 03/09/15.
 */
public class Issue192 {

    public static void main(String[] args) throws ParseException {
        String code = "public class StepImplementation {\n" +
                "    @Step(\"A step\")\n" +
                "    public void contextStep() {\n" +
                "        // Foo bar\n" +
                "    }\n" +
                "}";
        InputStream stream = new ByteArrayInputStream(code.getBytes(StandardCharsets.UTF_8));
        CompilationUnit cu = JavaParser.parse(stream);
        lookInto(cu);
    }

    private static void lookInto(Node node) {
        if (node.getOrphanComments() != null && node.getOrphanComments().size() > 0) {
            System.out.println("GOTCHA in " + node.getClass().getCanonicalName());
        }
        for (Node child : node.getChildrenNodes()) {
            lookInto(child);
        }
    }

}
```

print:

``` java
GOTCHA in com.github.javaparser.ast.stmt.BlockStmt
```

Our idea for comments attribution is to make easy to perform refectoring: we associate comments to the thing they are commenting and we move them together. However comments can be everywhere and the ones which are not associated to a particular element have to be treated specifically. I am sorry about these issues. I will work on more tests based on this use cases and fix this.

**Comment by ftomassetti** [comment]
case 1: GOTCHA in com.github.javaparser.ast.stmt.BlockStmt (the body of the method)
case 2: GOTCHA in com.github.javaparser.ast.stmt.BlockStmt (the body of the for loop)
case 3: nothing to check :)
case 4: GOTCHA in com.github.javaparser.ast.stmt.BlockStmt (the body of the for loop)

**Comment by ftomassetti** [comment]
Ok, I wrote a few additional tests and they are all parsing on master. I think the commit fixing the issue was not part of this release, doing a diff with `git diff master javaparser-parent-2.2.2`

I get:

```
--- a/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/DumpVisitor.java
+++ b/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/DumpVisitor.java
@@ -1131,7 +1131,6 @@ public final class DumpVisitor implements VoidVisitor<Object> {
            }
            printer.unindent();
        }
-       printOrphanCommentsEnding(n);
        printer.print("}");

    }
```

~~@SmiddyPence did you do the release from1 master or from branch developing-2.1?
When I sent the PR for #183 I sent it against master instead of the version 2 branch. This probably caused the misunderstanding. I am sorry abou that.~~

_Something seems missing from the master branch_
- Should we create a new branch for development (developing-2.2)?
- Should we do a new release? Could we just publish snapshots?
- ~~@mahendrakariya are you ok using master in the meantime?~~
  @mahendrakariya the patch in #183 should fix your issue but it was not included in the release, we are trying to understand why
- I will send a PR anyway with extra test cases derived from the examples kindly provided by @mahendrakariya so to be sure to avoid regressions

@mahendrakariya thank you again for your nice bug reports and your patience!

**Comment by mahendrakariya** [comment]
Thanks @ftomassetti for trying out all the cases and fixing it. It would be great if a snapshot release is made available until a stable version is released.

**Comment by mahendrakariya** [comment]
Are there any updates on this issue?

**Comment by ftomassetti** [comment]
Hi, I think all these issues should be solved with the current release. I have also created additional tests to verify these scenarios (#195) and it seems to me that they are passing. Could you please show me which code is not working as expected?

**Comment by mahendrakariya** [comment]
Very sorry for a delayed response. Was stuck with something else.
This issue is resolved in v2.3.0.

Thanks a lot!

**Comment by ftomassetti** [comment]
No problem, I am just happy it works now. I am sorry it took a while,next time we will react faster.

**Comment by vidyat11** [comment]
The JAPA Framework v2.3.0 by default does not have the capability to restore whole orphan comments in Class structure. 
It has the capability to restore only non-orphan comments. 

For ex:: Before CQC

/**
* 
 * @param a
* @param b
* @return
*/
    public int add(int a, int b) {
        // Noncompliant
        a = a + b;
        // Noncompliant
        // Seems like the parameter is returned as is
        return a;
    }
}

After CQC:: /**
* 
 * @param a
* @param b
* @return
*/
    public int add(int a, int b) {
        // Noncompliant
        a = a + b;
        // Seems like the parameter is returned as is, what is the point?
        return a;
    }
}
could please tell me which version have to use for solve this issues

**Comment by ftomassetti** [comment]
Well, almost 2 years are passed now, so I suggest you move to JavaParser 3.2.10 and verify if the problem is still present.

Version 2.3.0 is not supported anymore.

**Comment by vidyat11** [comment]
Thanks for the quick reply. I will check and update you

**Comment by vidyat11** [comment]
Still am facing the same problem

**Comment by matozoid** [comment]
@ftomassetti - I'm keeping the comment support issues open until we rewrite the whole thing.

**Comment by ftomassetti** [comment]
Yes, when we will discuss the big picture we should probably put the comment support rewriting among the priorities

**Comment by vidyat11** [comment]
@ftomassetti Any other version will support for this issues

**Comment by ftomassetti** [comment]
@vidyat11 I am not sure what you mean

**Comment by matozoid** [comment]
@vidyat11 the current approach to comments can never completely restore all comments in the correct position. We are rethinking comment support in issue #638.

**Comment by vidyat11** [comment]
@matozoid thanks for reply

**Comment by matozoid** [comment]
@ftomassetti - oh, sorry for my comments here. I see that @vidyat11 reopened this issue with another issue.

@vidyat11 - please open another issue, I just wasted my time trying to fix the issue from @mahendrakariya ...
