### ISSUE TITLE
`NoClassDefFoundError` on `new CompilationUnit()` when using Byte Buddy agent on Java 10+

### ISSUE THREAD

**Issue by l0rinc** [javaparser/javaparser#1926]
Hey,

Using:
- `implementation(group = "com.github.javaparser", name = "javaparser-core", version = "3.7.1")`
- `implementation(group = "net.bytebuddy", name = "byte-buddy", version = "1.9.3")` 
- OpenJDK (or Zulu) `10.0.2` or `11.0.1`

I'm getting:
```java.lang.NoClassDefFoundError: Could not initialize class com.github.javaparser.ast.CompilationUnit``` for `new CompilationUnit()` if there is an agent in the args, like `-javaagent:path/agent.jar`.

You can try it with https://github.com/javaparser/javaparser/wiki/Manual#creating-a-compilationunit-from-scratch

**Comment by matozoid** [comment]
Hi! Does #1925 help?

**Comment by l0rinc** [comment]
Thanks @matozoid, it could, when can a release be expected? Or how can I validate it?

**Comment by matozoid** [comment]
You can check out that branch and build it, then use that snapshot (it's in my clone of the repo), or you can wait until Sunday's release, because I think I'm mostly done with that PR now.

**Comment by matozoid** [comment]
(Honestly I have no idea what influence an agent should have on something as basic as JP-core, so I'm assuming the JDK version is the problem.)

**Comment by l0rinc** [comment]
The above example is working without the agent on Java 10, it fails only after adding it

**Comment by l0rinc** [comment]
It does seem to be working with Java 8 + agent, though

**Comment by matozoid** [comment]
Two potential problems fixed in that PR: I was accidentally using a "@Generated" annotation from a package that was split off into a module, and Mockito was upgraded (which upgrades bytebuddy.)

**Comment by matozoid** [comment]
Any improvement now?

**Comment by l0rinc** [comment]
Hey @matozoid, thanks for your efforts.
Unfortunately I'm still getting the following (`jdk 11.0.1-zulu`, `byte-buddy-dep:1.9.5`, `javaparser-core:3.8.0`):
```
java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedMethodAccessor14
 at jdk.internal.reflect.GeneratedMethodAccessor14.<clinit>(Unknown Source)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 at java.base/java.lang.Class.newInstance(Class.java:584)
 at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:404)
 at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
 at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at com.github.javaparser.ast.DataKey.<clinit>(DataKey.java)
 at com.github.javaparser.ast.Node.<clinit>(Node.java:708)
```

**Comment by matozoid** [comment]
Is it this one? https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8174817

**Comment by l0rinc** [comment]
No, that was solved in Java 9 & 10 and the above happens with 11, too.
Could it be a byte buddy bug in reality, @raphw?

**Comment by raphw** [comment]
What is the agent doing? If it instruments core classes, it probably is a class loading circularity triggered by a specific class loading order.

**Comment by l0rinc** [comment]
@matozoid, @raphw, I've created a simple project demonstrating the issue: https://github.com/paplorinc/JP_BB_NCDFE

**Comment by raphw** [comment]
The example agent is too invasive. By instrumenting all (!) classes, if a class is loaded during an instrumentation will cause a circularity. This will cause the class loading to fail which causes the no class def found error. You should better scope your instrumentation. Also, try logging the classes you instrument and see what classes are loaded right before the failed class loading.

**Comment by l0rinc** [comment]
How can an excessive anything cause a reference to an invalid class/method?

**Comment by raphw** [comment]
A class that is being instrumented can fail to load and not be available as a consequence. It is not expected behavior but class loading failures can look quite weird on a stack trace. Try setting `.disableClassFormatChanges()` what might help by making the instrumentation less invasive.

**Comment by l0rinc** [comment]
I'll try thanks. I have a feeling this is different, though, since `internal` classes cannot usually be accessed in Java 9+ (i.e. `jdk/internal/reflect/GeneratedMethodAccessor14`)

**Comment by raphw** [comment]
An important change is that Java 9 loads many classes on the platform class loader and not the bootstrap loader. The bootstrap loader is ignored by default, the platform loader is not. (Maybe that would be a good default.) Try excluding the platform loader to in the context of this problem.

**Comment by l0rinc** [comment]
Something may need the `jdk.unsupported`, the mentioned `jdk/internal/reflect/GeneratedMethodAccessor` usage is probably from http://hg.openjdk.java.net/jdk9/jdk9/jdk/file/65464a307408/src/java.base/share/classes/jdk/internal/reflect/MethodAccessorGenerator.java#l767

I still think there's a bug somewhere, but it's probably not in `javaparser`, so I'll cose the issue.
Thank you @raphw for your involvement, by using `.disableBootstrapInjection()` I don' see the error anymore - in the demo app at least.

**Comment by l0rinc** [comment]
Btw, @raphw the exception is first thrown when `net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport` is being instantiated (see: `java.base/jdk/internal/loader/BuiltinClassLoader.java:583`) - even when the behavior is correct, though.

**Comment by matozoid** [comment]
Good luck then :-)
