### ISSUE TITLE
Can't find its parameter type declared in another jar file for a method declared in a jar file.

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#3138]
I'm trying to get the method signature using this one:
```java
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JarTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class Test1 {
    public static void main(String[] args) throws IOException {
        Path pathToJar1 = Paths.get("/Users/liuyuan/Downloads/dataset/traccar-4.6/libs/jackson-databind-2.9.9.jar");
        Path pathToJar2 = Paths.get("/Users/liuyuan/Downloads/dataset/traccar-4.6/libs/jackson-core-2.9.9.jar");
        ParserConfiguration config = new ParserConfiguration();
        CombinedTypeSolver cts = new CombinedTypeSolver();
        cts.add(new ReflectionTypeSolver(false));
        cts.add(new JarTypeSolver(pathToJar1));
        cts.add(new JarTypeSolver(pathToJar2));
        config.setSymbolResolver(new JavaSymbolSolver(cts));
        StaticJavaParser.setConfiguration(config);

        String str = "import com.fasterxml.jackson.databind.SerializationConfig;\n"
                + "import com.fasterxml.jackson.databind.SerializationFeature;\n" + "public class Foo {\n"
                + "  void a() {\n" + "    SerializationConfig serializationConfig = new SerializationConfig();\n"
                + "    serializationConfig.without(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);\n"
                + "  }\n" + "}\n";

        CompilationUnit cu = StaticJavaParser.parse(str);
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        System.out.println(mce);
        System.out.println(mce.resolve().getQualifiedSignature());
    }
}
```

The test case above is:
```java
import com.fasterxml.jackson.databind.SerializationConfig;
import com.fasterxml.jackson.databind.SerializationFeature;
public class Foo {
  void a() {
    SerializationConfig serializationConfig = new SerializationConfig();
    serializationConfig.without(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
  }
}
```

In `SerializationConfig` class, there are multiple `without` method:
```java
public SerializationConfig without(SerializationFeature feature){...}
public SerializationConfig without(JsonGenerator.Feature feature){...}
public SerializationConfig without(FormatFeature feature){...}
```
`SerializationFeature` is declared in `jackson-databind-2.9.9.jar`. `FormatFeature` and `JsonGenerator`( whose inner type is `Feature`) are declared in `jackson-core-2.9.9.jar`. 

I get this exception:
```java
javassist.NotFoundException: com.fasterxml.jackson.core.JsonGenerator$Feature
```

**Comment by ghost** [comment]
Please find the attached (jackson-databind-2.9.9.jar & jackson-core-2.9.9.jar).
[libs.zip](https://github.com/javaparser/javaparser/files/6090608/libs.zip)

**Comment by jlerbsc** [comment]
Normally this issue was resolved this morning. Can you use the current snapshot and tell us if you have always this issue?

**Comment by ghost** [comment]
@jlerbsc Hi, this issue may still exist. I'm using the latest JavaParser (3.20.0), but it also throws the above errors.
```java
Exception in thread "main" java.lang.RuntimeException: javassist.NotFoundException: com.fasterxml.jackson.core.JsonGenerator$Feature
        at com.github.javaparser.symbolsolver.javassistmodel.JavassistMethodDeclaration.getNumberOfParams(JavassistMethodDeclaration.java:143)
        at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getSignature(ResolvedMethodLikeDeclaration.java:67)
        at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getQualifiedSignature(ResolvedMethodLikeDeclaration.java:82)
        at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.lambda$distinctByKey$1(MethodResolutionLogic.java:493)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:675)
        at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:521)
        at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:501)
        at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.solveMethod(JavassistClassDeclaration.java:259)
        at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:806)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:177)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:321)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:183)
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
        at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:317)
        at TestIssue3138.main(TestIssue3138.java:35)
Caused by: javassist.NotFoundException: com.fasterxml.jackson.core.JsonGenerator$Feature
        at javassist.ClassPool.get(ClassPool.java:430)
        at javassist.bytecode.Descriptor.toCtClass(Descriptor.java:571)
        at javassist.bytecode.Descriptor.getParameterTypes(Descriptor.java:424)
        at javassist.CtBehavior.getParameterTypes(CtBehavior.java:323)
        at com.github.javaparser.symbolsolver.javassistmodel.JavassistMethodDeclaration.getNumberOfParams(JavassistMethodDeclaration.java:141)
        ... 21 more
```
Is there any setting should I perform? Thanks.

**Comment by jlerbsc** [comment]
Hi @liuyuanOUC there was a revert on this PR this weekend (beyond my control). I don't know exactly why? It seemed that this PR was blocking the build of the project. It's amazing. I will be looking more specifically at this in these days.

**Comment by ghost** [comment]
Hi @jlerbsc thank you for your efforts on this wonderful project, and your attention on this issue. Hope everything goes well.

**Comment by maartenc** [comment]
Hi @liuyuanOUC , I don't know if it is possible for you to test if the PR #3167 solves your problem?

**Comment by ghost** [comment]
@jlerbsc Thanks for letting me know. I'm testing it.

**Comment by ghost** [comment]
thank you @jlerbsc Well done. It works.

**Comment by jlerbsc** [comment]
@liuyuanOUC I had nothing to do with it, it was maartenc who made the change ... so thank you @maartenc ;-)
