### ISSUE TITLE
Lazy types cause stack overflow when trying to find the least upper bound type

### ISSUE THREAD

**Issue by dimizisis** [javaparser/javaparser#3278]
Hello,

I am facing this issue with specific projects. One of them is [Apache SIS](https://github.com/apache/sis) and specifically in the core/sis-utility source root. I have the same problem with [Apache Oozie](https://github.com/apache/oozie), and specifically in the oozie/core source root.

Here is the initialization of the components of javaparser (version 3.22.1):

```java

ProjectRoot projectRoot = new SymbolSolverCollectionStrategy()
                .collect(Paths.get(getCurrentProject()));
List<SourceRoot> sourceRoots = projectRoot.getSourceRoots();

TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(getCurrentProject()));
JavaSymbolSolver symbolSolver = new JavaSymbolSolver(javaParserTypeSolver);
ParserConfiguration parserConfiguration = new ParserConfiguration();
parserConfiguration
                .setSymbolResolver(symbolSolver);
StaticJavaParser
                .setConfiguration(parserConfiguration);
```

And the way I am parsing the source roots:

```java
sourceRoots
  .stream()
  .forEach(sourceRoot -> {
    try {
      Streams.stream(ProgressBar.wrap(sourceRoot.tryToParse(), sourceRoot.getRoot().toString()))
        .filter(res -> res.getResult().isPresent())
        .forEach(res -> analyzeCompilationUnit(res.getResult().get(), sourceRoot.getRoot().toString()));
    } catch (Exception ignored) {}
  });
```

I am not sure where the error comes from (obviously from a resolved type). You can find the erros both for SIS & Oozie below:

<details><summary>The full error for Apache SIS</summary>
<p>

```
sis\core\sis-utility\src\main\java  45% ??? 100/221 (0:00:58 / 0:01:1Exception in thread "main" java.lang.StackOverflowError
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4337)
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4749)
        at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4713)
        at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4863)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4344)
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4749)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4747)
        at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3964)
        at java.base/java.util.regex.Pattern$Start.match(Pattern.java:3619)
        at java.base/java.util.regex.Matcher.search(Matcher.java:1729)
        at java.base/java.util.regex.Matcher.find(Matcher.java:773)
        at java.base/java.util.Formatter.parse(Formatter.java:2702)
        at java.base/java.util.Formatter.format(Formatter.java:2655)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:2897)
        at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserTypeParameter.getQualifiedName(JavaParserTypeParameter.java:141)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParametersMap.getValue(ResolvedTypeParametersMap.java:107)
        at com.github.javaparser.resolution.types.ResolvedReferenceType.typeParamValue(ResolvedReferenceType.java:385)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:49)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
        at ... (continues this way)
```
</p>
</details>

<details><summary>The full error for Apache Oozie</summary>
<p>

```
Exception in thread "main" java.lang.StackOverflowError
        at com.github.javaparser.ast.Node.hasScope(Node.java:1127)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:97)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:118)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:54)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:102)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:118)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:54)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:102)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:118)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:54)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:102)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:118)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:54)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:102)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:118)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:54)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:102)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:118)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:54)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:102)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:118)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:757)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ObjectCreationContext.solveType(ObjectCreationContext.java:54)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
        at (continues as above)
```

</p>
</details>

Thanks in advance!

**Comment by jlerbsc** [comment]
Hi @dimizisis thank you for reporting this issue but can you provide us a simple test case that reproduces it.

**Comment by dimizisis** [comment]
Hello, thanks for the reply. I'm providing my testcase below:

```java
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.model.resolution.TypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import org.junit.Test;

import java.io.File;

public class StackOverFlowTestCase {
    @Test
    public void g() {
        String code =
                "\n"+
                        "package org.apache.sis.measure;\n"+
                        "\n"+
                        "import java.util.Objects;\n"+
                        "import java.util.Formatter;\n"+
                        "import java.util.Formattable;\n"+
                        "import java.util.FormattableFlags;\n"+
                        "import java.io.Serializable;\n"+
                        "import javax.measure.Unit;\n"+
                        "import org.apache.sis.internal.util.Strings;\n"+
                        "import org.apache.sis.util.collection.CheckedContainer;\n"+
                        "import org.apache.sis.util.ArgumentChecks;\n"+
                        "import org.apache.sis.util.Emptiable;\n"+
                        "import org.apache.sis.util.Numbers;\n"+
                        "public class Range<E extends Comparable<? super E>> implements CheckedContainer<E>, Formattable, Emptiable, Serializable {\n"+
                        "    private static final long serialVersionUID = 603508245068333284L;\n"+
                        "    final Class<E> elementType;\n"+
                        "    final E minValue, maxValue;\n"+
                        "    final boolean isMinIncluded, isMaxIncluded;\n"+
                        "    public Range(final Range<E> range) {\n"+
                        "        elementType   = range.elementType;\n"+
                        "        minValue      = range.minValue;\n"+
                        "        isMinIncluded = range.isMinIncluded;\n"+
                        "        maxValue      = range.maxValue;\n"+
                        "        isMaxIncluded = range.isMaxIncluded;\n"+
                        "        assert validate() : elementType;\n"+
                        "    }\n"+
                        "    public Range(final Class<E> elementType,\n"+
                        "            final E minValue, final boolean isMinIncluded,\n"+
                        "            final E maxValue, final boolean isMaxIncluded)\n"+
                        "    {\n"+
                        "        ArgumentChecks.ensureNonNull(\"elementType\", elementType);\n"+
                        "        this.elementType   = elementType;\n"+
                        "        this.minValue      = minValue;\n"+
                        "        this.isMinIncluded = isMinIncluded && (minValue != null);\n"+
                        "        this.maxValue      = maxValue;\n"+
                        "        this.isMaxIncluded = isMaxIncluded && (maxValue != null);\n"+
                        "        assert validate() : elementType;\n"+
                        "    }\n"+
                        "    Range<E> create(final E minValue, final boolean isMinIncluded,\n"+
                        "                    final E maxValue, final boolean isMaxIncluded)\n"+
                        "    {\n"+
                        "        return new Range<>(elementType, minValue, isMinIncluded, maxValue, isMaxIncluded);\n"+
                        "    }\n"+
                        "    @SuppressWarnings({\"unchecked\",\"rawtypes\"})                     // Generic array creation.\n"+
                        "    Range<E>[] newArray(final int length) {\n"+
                        "        return new Range[length];\n"+
                        "    }\n"+
                        "    Unit<?> unit() {\n"+
                        "        return null;\n"+
                        "    }\n"+
                        "    private boolean validate() {\n"+
                        "        ArgumentChecks.ensureCanCast(\"minValue\", elementType, minValue);\n"+
                        "        ArgumentChecks.ensureCanCast(\"maxValue\", elementType, maxValue);\n"+
                        "        return Comparable.class.isAssignableFrom(elementType);\n"+
                        "    }\n"+
                        "    @Override\n"+
                        "    public Class<E> getElementType() {\n"+
                        "        return elementType;\n"+
                        "    }\n"+
                        "    public E getMinValue() {\n"+
                        "        return minValue;\n"+
                        "    }\n"+
                        "    public boolean isMinIncluded() {\n"+
                        "        return isMinIncluded;\n"+
                        "    }\n"+
                        "    public E getMaxValue() {\n"+
                        "        return maxValue;\n"+
                        "    }\n"+
                        "    public boolean isMaxIncluded() {\n"+
                        "        return isMaxIncluded;\n"+
                        "    }\n"+
                        "    @Override\n"+
                        "    public final boolean isEmpty() {\n"+
                        "        if (minValue == null || maxValue == null) {\n"+
                        "            return false;                               // Unbounded: can not be empty.\n"+
                        "        }\n"+
                        "        final int c = minValue.compareTo(maxValue);\n"+
                        "        if (c < 0) {\n"+
                        "            return false;                               // Minimum is smaller than maximum.\n"+
                        "        }\n"+
                        "        return (c != 0) || !isMinIncluded || !isMaxIncluded;\n"+
                        "    }\n"+
                        "    public boolean isBounded() {\n"+
                        "        return minValue != null && maxValue != null;\n"+
                        "    }\n"+
                        "    public boolean contains(final E value) {\n"+
                        "        if (value == null) {\n"+
                        "            return false;\n"+
                        "        }\n"+
                        "        if (minValue != null) {\n"+
                        "            final int c = minValue.compareTo(value);\n"+
                        "            if (isMinIncluded ? (c > 0) : (c >= 0)) {\n"+
                        "                return false;\n"+
                        "            }\n"+
                        "        }\n"+
                        "        if (maxValue != null) {\n"+
                        "            final int c = maxValue.compareTo(value);\n"+
                        "            if (isMaxIncluded ? (c < 0) : (c <= 0)) {\n"+
                        "                return false;\n"+
                        "            }\n"+
                        "        }\n"+
                        "        return true;\n"+
                        "    }\n"+
                        "    public boolean contains(final Range<? extends E> range) {\n"+
                        "        return (compareMinTo(range.minValue, range.isMinIncluded ? 0 : -1) <= 0) &&\n"+
                        "               (compareMaxTo(range.maxValue, range.isMaxIncluded ? 0 : +1) >= 0);\n"+
                        "    }\n"+
                        "    public boolean intersects(final Range<? extends E> range) {\n"+
                        "        return (compareMinTo(range.maxValue, range.isMaxIncluded ? 0 : +1) <= 0) &&\n"+
                        "               (compareMaxTo(range.minValue, range.isMinIncluded ? 0 : -1) >= 0);\n"+
                        "    }\n"+
                        "    public Range<E> intersect(final Range<E> range) {\n"+
                        "        if (range.isEmpty()) return range;\n"+
                        "        if (this .isEmpty()) return this;\n"+
                        "        final Range<E> intersect, min, max;\n"+
                        "        min = compareMinTo(range.minValue, range.isMinIncluded ? 0 : -1) < 0 ? range : this;\n"+
                        "        max = compareMaxTo(range.maxValue, range.isMaxIncluded ? 0 : +1) > 0 ? range : this;\n"+
                        "        if (min == max) {\n"+
                        "            intersect = min;\n"+
                        "        } else {\n"+
                        "            intersect = create(min.minValue, min.isMinIncluded, max.maxValue, max.isMaxIncluded);\n"+
                        "        }\n"+
                        "        assert intersect.isEmpty() == !intersects(range) : intersect;\n"+
                        "        return intersect;\n"+
                        "    }\n"+
                        "    public Range<E> union(final Range<E> range) {\n"+
                        "        if (range.isEmpty()) return this;\n"+
                        "        if (this .isEmpty()) return range;\n"+
                        "\n"+
                        "        final Range<E> union, min, max;\n"+
                        "        min = compareMinTo(range.minValue, range.isMinIncluded ? 0 : -1) > 0 ? range : this;\n"+
                        "        max = compareMaxTo(range.maxValue, range.isMaxIncluded ? 0 : +1) < 0 ? range : this;\n"+
                        "        if (min == max) {\n"+
                        "            union = min;\n"+
                        "        } else {\n"+
                        "            union = create(min.minValue, min.isMinIncluded, max.maxValue, max.isMaxIncluded);\n"+
                        "        }\n"+
                        "        assert union.contains(min) : min;\n"+
                        "        assert union.contains(max) : max;\n"+
                        "        return union;\n"+
                        "    }\n"+
                        "    public Range<E>[] subtract(final Range<E> range) {\n"+
                        "        final Range<E> subtract;\n"+
                        "        if (!intersects(range)) {\n"+
                        "            subtract = this;\n"+
                        "        } else {\n"+
                        "            final boolean clipMin = compareMinTo(range.minValue, range.isMinIncluded ? 0 : -1) >= 0;\n"+
                        "            final boolean clipMax = compareMaxTo(range.maxValue, range.isMaxIncluded ? 0 : +1) <= 0;\n"+
                        "            if (clipMin) {\n"+
                        "                if (clipMax) {\n"+
                        "                    assert range.contains(this) : range;\n"+
                        "                    return newArray(0);\n"+
                        "                }\n"+
                        "                subtract = create(range.maxValue, !range.isMaxIncluded, maxValue, isMaxIncluded);\n"+
                        "            } else {\n"+
                        "                if (!clipMax) {\n"+
                        "                    final Range<E>[] array = newArray(2);\n"+
                        "                    array[0] = create(minValue, isMinIncluded, range.minValue, !range.isMinIncluded);\n"+
                        "                    array[1] = create(range.maxValue, !range.isMaxIncluded, maxValue, isMaxIncluded);\n"+
                        "                    return array;\n"+
                        "                }\n"+
                        "                subtract = create(minValue, isMinIncluded, range.minValue, !range.isMinIncluded);\n"+
                        "            }\n"+
                        "        }\n"+
                        "        assert contains(subtract) : subtract;\n"+
                        "        assert !subtract.intersects(range) : subtract;\n"+
                        "        final Range<E>[] array = newArray(1);\n"+
                        "        array[0] = subtract;\n"+
                        "        return array;\n"+
                        "    }\n"+
                        "    private int compareMinTo(final E value, int position) {\n"+
                        "        if (minValue == null) {\n"+
                        "            return (value == null) ? 0 : -1;\n"+
                        "        }\n"+
                        "        if (value == null) {\n"+
                        "            return -position;\n"+
                        "        }\n"+
                        "        final int c = minValue.compareTo(value);\n"+
                        "        if (c != 0) {\n"+
                        "            return c;\n"+
                        "        }\n"+
                        "        if (!isMinIncluded) {\n"+
                        "            position++;\n"+
                        "        }\n"+
                        "        return position;\n"+
                        "    }\n"+
                        "    private int compareMaxTo(final E value, int position) {\n"+
                        "        if (maxValue == null) {\n"+
                        "            return (value == null) ? 0 : +1;\n"+
                        "        }\n"+
                        "        if (value == null) {\n"+
                        "            return -position;\n"+
                        "        }\n"+
                        "        final int c = maxValue.compareTo(value);\n"+
                        "        if (c != 0) {\n"+
                        "            return c;\n"+
                        "        }\n"+
                        "        if (!isMaxIncluded) {\n"+
                        "            position--;\n"+
                        "        }\n"+
                        "        return position;\n"+
                        "    }\n"+
                        "    @Override\n"+
                        "    public boolean equals(final Object object) {\n"+
                        "        if (object == this) {\n"+
                        "            return true;\n"+
                        "        }\n"+
                        "        if (object != null && object.getClass() == getClass()) {\n"+
                        "            final Range<?> other = (Range<?>) object;\n"+
                        "            if (Objects.equals(elementType, other.elementType)) {\n"+
                        "                if (isEmpty()) {\n"+
                        "                    return other.isEmpty();\n"+
                        "                }\n"+
                        "                return Objects.equals(minValue, other.minValue) &&\n"+
                        "                       Objects.equals(maxValue, other.maxValue) &&\n"+
                        "                       isMinIncluded == other.isMinIncluded &&\n"+
                        "                       isMaxIncluded == other.isMaxIncluded;\n"+
                        "            }\n"+
                        "        }\n"+
                        "        return false;\n"+
                        "    }\n"+
                        "    @Override\n"+
                        "    public int hashCode() {\n"+
                        "        int hash = elementType.hashCode();\n"+
                        "        if (!isEmpty()) {\n"+
                        "            hash = 13 * hash + Objects.hashCode(minValue);\n"+
                        "            hash = 13 * hash + Objects.hashCode(maxValue);\n"+
                        "            hash += isMinIncluded ?   17 :   37;\n"+
                        "            hash += isMaxIncluded ? 1231 : 1237;\n"+
                        "        }\n"+
                        "        return hash ^ (int) serialVersionUID;\n"+
                        "    }\n"+
                        "    private static boolean isCompact(final Comparable<?> value, final boolean ifNull) {\n"+
                        "        if (value == null) {\n"+
                        "            return ifNull;\n"+
                        "        }\n"+
                        "        final long n = ((Number) value).longValue();\n"+
                        "        return n >= 0 && n < 10;\n"+
                        "    }\n"+
                        "    @Override\n"+
                        "    public String toString() {\n"+
                        "        if (isEmpty()) {\n"+
                        "            return \"{}\";\n"+
                        "        }\n"+
                        "        final StringBuilder buffer = new StringBuilder(20);\n"+
                        "        if (minValue != null && minValue.equals(maxValue)) {\n"+
                        "            buffer.append(\"{\").append(minValue).append(\"}\");\n"+
                "        } else {\n"+
                "            buffer.append(isMinIncluded ? \"[\" : \"(\");\n"+
                "            if (minValue == null) {\n"+
                "                buffer.append(\"−∞\");\n"+
                "            } else {\n"+
                "                buffer.append(minValue);\n"+
                "            }\n"+
                "            if (Numbers.isInteger(elementType) && isCompact(minValue, false) && isCompact(maxValue, true)) {\n"+
                "                buffer.append(\"…\");\n"+
                "            } else {\n"+
                "                buffer.append(\" … \");\n"+
                "            }\n"+
                "            if (maxValue == null) {\n"+
                "                buffer.append(\"∞\");\n"+
                "            } else {\n"+
                "                buffer.append(maxValue);\n"+
                "            }\n"+
                "            buffer.append(isMaxIncluded ? \"]\" : \")\");\n"+
                "        }\n"+
                "        final Unit<?> unit = unit();\n"+
                "        if (unit != null) {\n"+
                "            final String symbol = unit.toString();\n"+
                "            if (symbol != null && !symbol.isEmpty()) {\n"+
                "                if (Character.isLetterOrDigit(symbol.codePointAt(0))) {\n"+
                "                    buffer.append(\" \");\n"+
                "                }\n"+
                "                buffer.append(symbol);\n"+
                "            }\n"+
                "        }\n"+
                "        return buffer.toString();\n"+
                "    }\n"+
                "    @Override\n"+
                "    public void formatTo(final Formatter formatter, final int flags, final int width, int precision) {\n"+
                "        final String value;\n"+
                "        if (precision == 0) {\n"+
                "            value = \"\";\n"+
                "        } else {\n" +
                "            final RangeFormat format = new RangeFormat(formatter.locale(), elementType);\n"+
                "            format.setAlternateForm((flags & FormattableFlags.ALTERNATE) != 0);\n"+
                "            value = format.format(this, new StringBuffer(), null).toString();\n"+
                "        }\n"+
                "        Strings.formatTo(formatter, flags, width, precision, value);\n"+
                "    }\n"+
                "}\n"+
                "";
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File("."));
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(javaParserTypeSolver);
        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration
                .setSymbolResolver(symbolSolver);
        StaticJavaParser
                .setConfiguration(parserConfiguration);
        CompilationUnit cu = StaticJavaParser.parse(code);

        cu.findAll(ClassOrInterfaceDeclaration.class).forEach(classOrInterfaceDeclaration -> {
            classOrInterfaceDeclaration.getMethods().forEach(methodDeclaration -> {
                methodDeclaration.findAll(MethodCallExpr.class).forEach(methodCallExpr -> {
                    try {
                        System.out.println(methodCallExpr.resolve().getQualifiedName());
                    } catch (Exception e) {}
                });
            });
        });
    }
}
```

Thanks again,

Dimitris

**Comment by jlerbsc** [comment]
linked to https://github.com/javaparser/javaparser/issues/3972

**Comment by jlerbsc** [comment]
I'm closing this issue because I think it's definitely resolved by this PR (https://github.com/javaparser/javaparser/pull/4236). You can reopen it if this is not the case by providing a simplified test case.

**Comment by tongbaner** [comment]
Hi,
I still have a StackOverflowError after upgrading to the latest version, here is the code and testcase, hope it will be helpful.
code:
```
new SymbolSolverCollectionStrategy().collect(Paths.get(path))
			.getSourceRoots().forEach(root->{
			try {
				List<ParseResult<CompilationUnit>> cus = root.tryToParse();
				cus.forEach(cu->{
					cu.getResult().get().findAll(MethodCallExpr.class).forEach(mc->{
						mc.resolve();
					});
				});
			} catch (IOException e) {
			}
		});
```
test case:
```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Problem {
	private static Logger logger = LoggerFactory.getLogger(Problem.class);
	
    public static void main(String[] args) {
        A a = null;
        logger.trace("{}",(a==null? "null": a.getB()));
    }
}

class A{
    private B b;
    public A(B b){
        this.b = b;
    }
    public B getB(){
        return b;
    }
}

class B implements Comparable<B>{

	@Override
	public int compareTo(B o) {
		return 0;
	}
}
```
part of the stack trace
```
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at com.github.javaparser.ast.body.TypeDeclaration.lambda$getFullyQualifiedName$7(TypeDeclaration.java:206)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.github.javaparser.ast.body.TypeDeclaration.getFullyQualifiedName(TypeDeclaration.java:206)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.getFullyQualifiedName(ClassOrInterfaceDeclaration.java:242)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:128)
	at com.github.javaparser.resolution.Context.solveTypeInParentContext(Context.java:154)
	at com.github.javaparser.resolution.Context.solveType(Context.java:120)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationExtendsContext.solveType(ClassOrInterfaceDeclarationExtendsContext.java:51)
	at com.github.javaparser.resolution.Context.solveType(Context.java:97)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:345)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:607)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:639)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:635)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.lambda$null$5(JavaParserClassDeclaration.java:490)
	at com.github.javaparser.resolution.model.typesystem.LazyType.getType(LazyType.java:40)
	at com.github.javaparser.resolution.model.typesystem.LazyType.isReferenceType(LazyType.java:72)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$erasureOfParamaters$12(ResolvedReferenceType.java:583)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.erasureOfParamaters(ResolvedReferenceType.java:587)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.erasure(ResolvedReferenceType.java:575)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.github.javaparser.symbolsolver.resolution.typeinference.LeastUpperBoundLogic.lambda$erased$2(LeastUpperBoundLogic.java:252)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.github.javaparser.symbolsolver.resolution.typeinference.LeastUpperBoundLogic.erased(LeastUpperBoundLogic.java:253)
	at com.github.javaparser.symbolsolver.resolution.typeinference.LeastUpperBoundLogic.lub(LeastUpperBoundLogic.java:87)
	at com.github.javaparser.symbolsolver.resolution.typeinference.LeastUpperBoundLogic.lctaNoWildcard(LeastUpperBoundLogic.java:470)
	at com.github.javaparser.symbolsolver.resolution.typeinference.LeastUpperBoundLogic.lcta(LeastUpperBoundLogic.java:461)
	at com.github.javaparser.symbolsolver.resolution.typeinference.LeastUpperBoundLogic.leastContainingTypeArgument(LeastUpperBoundLogic.java:360)
	at com.github.javaparser.symbolsolver.resolution.typeinference.LeastUpperBoundLogic.leastContainingParameterization

**Comment by jlerbsc** [comment]
Hi,

Thank you for reporting this case. I slightly modified your example which does not compile (which is a prerequisite for using javaparser). With this test case I have no exceptions. Maybe you could complete it to highlight your problem.


    public class Problem {
	    public void main(String[] args) {
	        A a = null;
	        m(a.getB());
	    }
	    void m(B b) {}
	}

	class A{
	    private B b;
	    public A(B b){
	        this.b = b;
	    }
	    public B getB(){
	        return b;
	    }
	}

	class B implements Comparable<B>{

		@Override
		public int compareTo(B o) {
			return 0;
		}
	}

**Comment by tongbaner** [comment]
Hi,
Thanks for your quick reply, and I am sorry for the unclarity. I have modified the test case to make it compile. I think the reason that cause this exception for this case is when one of the arguements is a ConditionalExpr. Can you try again?

**Comment by jlerbsc** [comment]
It seems to be linked to the lazy type. Lazy types are types whose resolution is deferred.
