### ISSUE TITLE
Inferred lambda parameter type when the function is imported statically

### ISSUE THREAD

**Issue by abdullahtellioglu** [javaparser/javaparser#4917]
JavaParser is unable to resolve the `query -> taskService.list(toSpringPageRequest(query)).stream()` statement when `toSpringPageRequest` is imported statically from another class via `import static com.vaadin.flow.spring.data.VaadinSpringDataHelpers.toSpringPageRequest` . 

However, method call is resolved fine when `import static` is removed and the expression is changed to -> 
 `query -> taskService.list(VaadinSpringDataHelpers.toSpringPageRequest(query)).stream()`. 

Java parser version is: 3.27.1

// Example code
```java
import static com.vaadin.flow.spring.data.VaadinSpringDataHelpers.toSpringPageRequest;

public class TaskListView extends Main {

    private final TaskService taskService;
    final Grid<Task> taskGrid;

    public TaskListView(TaskService taskService) {
        this.taskService = taskService;
        taskGrid = new Grid<>();
        taskGrid.setItems(query -> taskService.list(toSpringPageRequest(query)).stream());
        add(taskGrid);
    }
}

```

// Exception that is thrown when method is imported statically
```java
java.lang.IllegalArgumentException: Inferred lambda parameter type
	at com.github.javaparser.ast.type.UnknownType.convertToUsage(UnknownType.java:148) ~[javaparser-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:678) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:709) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:705) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:69) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.resolution.model.Value.from(Value.java:46) ~[javaparser-core-3.27.1.jar:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ExpressionContext.solveSymbolAsValue(ExpressionContext.java:45) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:76) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:82) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:343) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:64) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:80) ~[javaparser-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:563) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:424) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:303) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:323) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:134) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:190) ~[javaparser-symbol-solver-core-3.27.1.jar:na]
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:332) ~[javaparser-core-3.27.1.jar:na]
```

**Comment by jlerbsc** [comment]
Can you provide a simplified unit test?

**Comment by abdullahtellioglu** [comment]
I failed to create a unit test as mimicking the real application in a unit test is not easy because the example contains multiple interfaces, functional interfaces and different classes. But I created a sample application in my repository if you would like to check. 

https://github.com/abdullahtellioglu/java-parser-generic-issue/blob/main/src/main/java/com/example/application/JavaParserTest.java

When you run the main function, it will throw an exception.

**Comment by jlerbsc** [comment]
In your example, it seems to me that the symbol resolver configuration is incomplete. You must declare the Vaadin libraries using the JarTypeSolver class.

**Comment by abdullahtellioglu** [comment]
In the example, ReflectionTypeSolver gets false, which should resolve ALL_CLASSES, am I right? Also, I updated the code by adding 
```java
       String classPath = System.getProperty("java.class.path");
        for (String entry : classPath.split(File.pathSeparator)) {
            if(entry.endsWith(".jar")) {
                try{
                    combinedTypeSolver.add(new JarTypeSolver(entry));
                }catch (IOException ex){
                    System.out.println("Can't find class path: " + entry);
                }

            }
        }
```
all classes in the classpath as JarTypeSolver. The result is the same

**Comment by jlerbsc** [comment]
There is indeed a bug, probably related to type inference. It will be difficult to fix because the test case is not straightforward. Thank you for reporting it..

**Comment by jlerbsc** [comment]
Note: The expression  taskGrid.setItems(query -> taskService.list(toSpringPageRequest(query)).stream()) is solved correctly to

    com.vaadin.flow.data.provider.HasLazyDataView.setItems(com.vaadin.flow.data.provider.CallbackDataProvider.FetchCallback<T, F>)

but taskService.list(toSpringPageRequest(query)).stream() fails

**Comment by jlerbsc** [comment]
Do you still have this issue with the current snapshot version?

**Comment by abdullahtellioglu** [comment]
Upgraded the project to the latest version - 3.28.0- and the exception still occurs
